Module5 task1
htmlacademy-javascript/2156249-keksobooking-1 pull request #1
Opened 2024-05-22 12:35 UTC by DariaEgarmina

2024-05-22 14:18 UTC, wonderjs requested changes

2024-05-22 14:18 UTC, wonderjs commented on js/functions.js
> +  if (a < 0 || b < 0) {
Тут ещё можно добавить проверку на то, что decimalPlaces не отрицательное число

2024-05-22 14:18 UTC, wonderjs commented on js/main.js
> +import { createSimilarAnnouncements } from "./data.js";
Одинарные кавычки, не забывай про линтер)

2024-05-22 14:18 UTC, wonderjs commented on js/data.js
> +  const amount = getRandomInteger(1, features.length - 1);
Что в этой функции не очень:
Функция getRandomInteger(1, features.length - 1) вернет случайное число от 1 до features.length - 1, что может привести к неправильной выборке. Те если Если start >= amount, вернется весь массив features. 
Код не перемешивает элементы массива, что означает, что подмножество будет всегда содержать последовательные элементы оригинального массива.

Простое решение: 
```

const getRandomElements = () => Math.random() - 0.5;

const createFeatures = (features) => {
  const shuffledFeatures = features.sort(getRandomElements);
  const featuresCount = getRandomPositiveInteger(0, features.length);
  return shuffledFeatures.slice(0, featuresCount);
};
```

По шагам: 
1) Перемешивание массива:
`const shuffledFeatures = features.sort(getRandomElements);`
Здесь массив features перемешивается с использованием метода sort и функции getRandomElements. Функция getRandomElements возвращает случайное число, что приводит к случайной перестановке элементов массива.

2) Определение случайного количества элементов:
`const featuresCount = getRandomPositiveInteger(0, features.length);`
Здесь определяется случайное количество элементов, которые нужно выбрать из перемешанного массива. Используется функция getRandomPositiveInteger, которая возвращает случайное целое число в заданном диапазоне (от 0 до features.length).

3) Создание нового массива с выбранным количеством элементов:
`return shuffledFeatures.slice(0, featuresCount);`
В итоге используется метод slice, чтобы выбрать featuresCount элементов из перемешанного массива, начиная с индекса 0.

2024-05-22 14:18 UTC, wonderjs commented on js/data.js
> +const LAT = {
[Б8.](https://up.htmlacademy.ru/javascript-individual/1/criteries#b8) Название классов, конструкторов и перечислений начинается с **заглавной буквы**. В названии используются английские существительные. Значения перечислений объявлены как **константы**.
```
const Lat = {
  MIN: 35.65000,
  MAX: 35.70000,
};
```
Lng ниже тоже поправить

2024-05-22 14:18 UTC, wonderjs commented on js/data.js
> +const createAdress = (loc) => {
Проще + исправить опечатку в названии
```
const createAddress = (loc) => `${loc.lat}, ${loc.lng}`;
```

2024-05-22 14:18 UTC, wonderjs commented on js/data.js
> +const hotelLocaion = createLocation();
Не пойдет, так у тебя у всех объявлений будет одна локация

2024-05-22 14:18 UTC, wonderjs commented on js/util.js
> +const getRandomInfiniteNumber = () => {
Функция из интернета? Ты ее понимаешь? Используешь ее только для генерации цены, проще придумать какие-то мин/макс значения и использовать `getRandomInteger`

2024-05-22 14:18 UTC, wonderjs commented on js/data.js
> +const createPhotos = (photos) => {
createActualFeatures и createPhotos выглядят ооочень похожими, давай обойдемся одной

2024-05-22 14:18 UTC, wonderjs commented on js/data.js
> +  const randomDescriptionIndex = getRandomInteger(0, DESCRIPTIONS.length - 1);
Тебе явно нужна функция, которая будет сразу возвращать рандомный элемент массива без создания промежуточных переменных с индексом

2024-05-22 14:18 UTC, wonderjs commented on js/data.js
> +const createAnnouncement = () => (
Announcement cложно слово =) можно проще Ad - сокращение от advertisement (объявление)

2024-05-23 09:07 UTC, DariaEgarmina commented on js/data.js
> +const hotelLocaion = createLocation();
Тут у меня затык с тем, чтобы сделать адрес и локацию идентичными :(((

2024-05-23 09:22 UTC, DariaEgarmina commented on js/data.js
> +  const amount = getRandomInteger(1, features.length - 1);
Может, в пункте 2 лучше сделать от 1 до features.length - иначе иногда получаются пустые массивы

2024-05-23 09:25 UTC, wonderjs commented on js/data.js
> +const hotelLocaion = createLocation();
Внутри функции createAnnouncement создаешь локацию и записываешь в переменную:
```
const location = createLocation();
```
Потом передаешь эту локацию при вызове функции createOffer:
```
{
  ...
  location: createOffer(location),
}
```
Внутри createOffer используем location: 
```
{
  ...
  address: createAddress(location),
  ...
}
```

2024-05-23 09:32 UTC, wonderjs commented on js/data.js
> +  const amount = getRandomInteger(1, features.length - 1);
Можно, но не обязательно, в нашем случае теоретически можно представить что какое-то из объявлений может не иметь фич и нам нужно будет обработать этот кейс при отображении данных. Если по условию задачи массив точно не может быть пустым, тогда да, берем 1, а не 0.

2024-05-23 12:07 UTC, closed without merging