7.15. Отрисуй меня полностью
htmlacademy-javascript/2156249-keksobooking-1 pull request #3
Opened 2024-05-28 11:43 UTC by DariaEgarmina

2024-05-28 12:57 UTC, wonderjs requested changes

2024-05-28 12:57 UTC, wonderjs commented on js/render-ads.js
> +const renderAds = (ads) => {
Тебе не нужна функция, которая будет рендерить все карточки. Одновременно может быть показана только одна. Так что упрости функцию до renderAd и передавай внутрь только одно объявление (один объект)

2024-05-28 12:57 UTC, wonderjs commented on js/render-ads.js
> +      adElement.querySelector('.popup__type').textContent = 'Дворец';
Заведи себе словарик, который будет переводить тип в текст:
```
const typeMap = {
  flat: 'Квартира',
  bungalow: 'Бунгало',
  house: 'Дом',
  palace: 'Дворец',
  hotel: 'Отель'
};
```

2024-05-28 12:57 UTC, wonderjs commented on js/render-ads.js
> +const createFeatures = (adElement, ad) => {
Вторым параметром здесь можно сразу передавать features

2024-05-28 12:57 UTC, wonderjs commented on js/render-ads.js
> +    const modifier = featureListItem.classList[1];
Скользкий момент завязываться на номер класса элемента. 

Как лучше сделать:
1) Проверить что features вообще есть и массив не пустой, иначе удалить блок
3) Тут создать фрагмент, пройтись по массиву фич, создать элемент li с нужными классом,  добавить в фрагмент
4) Добавить фрагмент в контейнер

2024-05-28 12:57 UTC, wonderjs commented on js/render-ads.js
> +    photoContainer.innerHTML = '';
1) добавить проверку что ключ photos вообще существует
2) Лучше удалить блок из разметки блок, через remove(); либо выставить display: none . Тк у блока есть внешние отступы, которые будут влиять на другие блоки даже если внутри ничего не будет. Аналогично для всех остальных блоков в разметке. Либо прям удалить, либо скрыть.

2024-05-28 12:57 UTC, wonderjs commented on js/render-ads.js
> +      photo.src = `${offerPhoto}`;
зачем здесь обратные кавычки? 
просто `photo.src = offerPhoto;`

2024-05-28 12:57 UTC, wonderjs commented on js/render-ads.js
> +const createPhotos = (adElement, ad) => {
Вторым параметром передать сразу photos

2024-05-28 12:57 UTC, wonderjs commented on js/render-ads.js
> +  adElement.querySelector('.popup__text--time').textContent = `Заезд после ${ad.offer.checkin}, выезд до ${ad.offer.checkout}`;
Предусмотреть кейс, когда данные не пришли, чтобы пользователь не увидел такого =) 
![Снимок экрана 2024-05-28 в 14 47 26](https://github.com/htmlacademy-javascript/2156249-keksobooking-1/assets/25072556/49985483-0366-46d8-9c9d-e09123969c8e)
В целом тебе нужно написать проверки на все ключи. Подсказка: тебе нужно функция, которая будет принимать элемент, какой атрибут нужно заполнить и значение. И либо будет заполнять атрибут, либо удалять/ скрывать элемент, если значения нет
```
const fillElementAttribute = (element, attribute, value) => {
  if (value) {
    element[attribute] = value;
  } else {
    element.remove(); // или скрытие через display none
  }
};
```
В целом эта функция + **дополнительные доработки** поможет тебе с ключами title, address, price, rooms, guests, checkin, checkout, description, src. Пофантазируй, если идей не будет - пиши.

2024-06-08 11:14 UTC, DariaEgarmina commented on js/render-ads.js
> +const createFeatures = (adElement, ad) => {
тут вот я пока не очень поняла, как это сделать

2024-06-08 13:13 UTC, DariaEgarmina commented on js/render-ads.js
> +      photo.src = `${offerPhoto}`;
я вспомнила, как делать конкатенацию, и решила вставить ее везде :)))))

2024-06-08 13:14 UTC, DariaEgarmina commented on js/render-ads.js
> +const createPhotos = (adElement, ad) => {
аналогично как с features, я тут туплю

2024-06-08 14:39 UTC, DariaEgarmina commented on js/render-ads.js
> +  adElement.querySelector('.popup__text--time').textContent = `Заезд после ${ad.offer.checkin}, выезд до ${ad.offer.checkout}`;
Тут у меня тоже не получилось. Самое главное, что я не понимаю эту запись element[attribute] = value; Меня смутили скобки. Вроде же доступ к атрибутам мы получаем через точку

2024-06-09 09:51 UTC, DariaEgarmina commented on js/render-ads.js
> +  adElement.querySelector('.popup__text--time').textContent = `Заезд после ${ad.offer.checkin}, выезд до ${ad.offer.checkout}`;
атрибут ведь это "class", "id", "href", а заполнить нам нужно в основном textContent - а это свойство элемента, и непонятно как его "вставить в переменную"

2024-06-09 10:40 UTC, DariaEgarmina commented on js/render-ads.js
> +  adElement.querySelector('.popup__text--time').textContent = `Заезд после ${ad.offer.checkin}, выезд до ${ad.offer.checkout}`;
"undefined комнаты для гостей" - когда у меня такая ситуация, я не могу удалить элемент из дом, а также не могу очистить его innerHTML :( в этом затык

2024-06-10 08:02 UTC, wonderjs commented on js/render-ads.js
> +const createFeatures = (adElement, ad) => {
При вызове функции передаешь сразу features
`createFeatures(adElement, ad.features)`

2024-06-10 08:02 UTC, wonderjs commented on js/render-ads.js
> +const createPhotos = (adElement, ad) => {
`createPhotos(adElement, ad.photos);`

2024-06-10 08:08 UTC, wonderjs commented on js/render-ads.js
> +  adElement.querySelector('.popup__text--time').textContent = `Заезд после ${ad.offer.checkin}, выезд до ${ad.offer.checkout}`;
element.textContent === element['textContent']

2024-06-10 08:10 UTC, wonderjs commented on js/render-ads.js
> +  adElement.querySelector('.popup__text--time').textContent = `Заезд после ${ad.offer.checkin}, выезд до ${ad.offer.checkout}`;
"undefined комнаты для гостей":

```
const getCapacity = (rooms, guests) => rooms && guests ? `${rooms} ${getRoomPlural(rooms)} для ${guests} гостей` : null;

fillElementAttribute(advertisementElement.querySelector('.popup__text--capacity'), 'textContent', getCapacity(ad.offer.rooms, ad.offer.guests));
```

2024-06-11 14:03 UTC, DariaEgarmina commented on js/render-ads.js
> +const createFeatures = (adElement, ad) => {
Не понятно, почему я с этим так долго тупила

2024-06-24 11:35 UTC, wonderjs commented on js/render-ad.js
> +  switch (ad.offer.type) {
Вместо switch, просто:
`adElement.querySelector('.popup__type').textContent = typeMap[ad.offer.type];`

2024-06-24 11:37 UTC, wonderjs requested changes

2024-06-24 11:37 UTC, wonderjs commented on js/render-ad.js
> +const renderAd = (ads) => {
Давай передавать не массив, в конкретный объект, который хотим отобразить

2024-06-25 09:58 UTC, wonderjs approved these changes

2024-06-25 09:58 UTC, merged