ДЗ 9.18. Помощь друга
htmlacademy-javascript/2156249-keksobooking-1 pull request #6
Opened 2024-07-03 12:27 UTC by DariaEgarmina

2024-07-04 09:52 UTC, wonderjs requested changes

2024-07-04 09:52 UTC, wonderjs commented on js/form.js
> -disableForm();
Это удалять не нужно

2024-07-04 09:52 UTC, wonderjs commented on js/form.js
>  document.addEventListener('DOMContentLoaded', () => {
А вот здесь нужно удалить весь обработчик

2024-07-04 10:19 UTC, wonderjs commented on js/map.js
> +    lng: 139.8302,
[Д19.](https://up.htmlacademy.ru/javascript-individual/1/criteries#d19) В коде не используются «магические значения», под каждое из них заведена отдельная переменная, названная как константа.
дефолтные координаты - в константу

2024-07-04 17:58 UTC, wonderjs commented on js/map.js
> +const DEFAULT_LOCATION = {
[Б8.](https://up.htmlacademy.ru/javascript-individual/1/criteries#b8) Название классов, конструкторов и перечислений начинается с заглавной буквы. Значения перечислений объявлены как константы.
Это перечисление 
```
const DefaultLocation = {
  LAT: ...,
  LNG: ...,
}
```

2024-07-04 17:58 UTC, wonderjs commented on js/map.js
> +addressFieldElement.readOnly = true;
прям в html можно прописать readonly

2024-07-04 17:58 UTC, wonderjs commented on js/map.js
> +    lng: 139.7823,
Дефолтная локация? Используем константу

2024-07-05 08:09 UTC, DariaEgarmina commented on js/map.js
> +const DEFAULT_LOCATION = {
Блин, пока всё время с этим путаюсь :(((

2024-07-05 13:27 UTC, wonderjs requested changes

2024-07-05 13:27 UTC, wonderjs commented on js/map.js
> +const similarAds = createSimilarAds();
Верни обратно в main =) будем передавать объявления в функцию рендера маркеров

2024-07-05 13:27 UTC, wonderjs commented on js/map.js
> +similarAds.forEach((similarAd) => {
Здесь нужны 2 функции - отрисовки одного маркера и отрисовки всех
```
const createMarker = (ad) => {
  const similarMarker = L.marker(
    {
      lat: ad.location.lat,
      lng: ad.location.lng,
    },
    {
      icon
    },
  );

  similarMarker
    .addTo(map)
    .bindPopup(createAdElement(ad));
};

const renderSimilarMarkers = (ads) => ads.forEach((similarAd) => createMarker(similarAd));
```

Экспортируем из модуля функцию renderSimilarMarkers, импортируем в модуль main, там вызываем и передаем туда массив объявлений

2024-07-05 13:27 UTC, wonderjs commented on js/map.js
> +const popupTemplate = document.querySelector('#card').content.querySelector('.popup');
А откуда здесь взялась эта переменная? Зачем?

2024-07-05 13:27 UTC, wonderjs commented on js/render-ad.js
>  const renderAd = (ad) => {
Кажется это функция нам больше не нужна, можно удалить.

2024-07-05 13:27 UTC, wonderjs commented on js/render-ad.js
> +const createAdElement = (ad, template) => {
Зачем добавила темплейт как параметр?

2024-07-05 13:27 UTC, wonderjs commented on js/render-ad.js
> -const similarAdTemplate = document.querySelector('#card').content.querySelector('.popup');
Непонятно зачем убрала =)

2024-07-09 10:32 UTC, DariaEgarmina commented on js/map.js
> +const popupTemplate = document.querySelector('#card').content.querySelector('.popup');
Это у меня мозг за мозг зашел

2024-07-09 10:52 UTC, DariaEgarmina commented on js/render-ad.js
> +const createAdElement = (ad, template) => {
по той же причине :)))

2024-07-09 14:34 UTC, merged