Module11 task1 Отправка и получение данных
htmlacademy-javascript/2156249-keksobooking-1 pull request #8
Opened 2024-07-22 11:13 UTC by DariaEgarmina

2024-07-23 14:58 UTC, wonderjs commented on js/api.js
> +// ?? ЧТО ДЕЛАТЬ С ERRORTEXT????
Можно добавить в ErrorText ключик 
`SEND_DATA: 'Не удалось отправить форму. Попробуйте ещё раз',`
и в sendData передавать его. 
Но по сути использоваться он нигде не будет, тк в нашей модалке с ошибкой уже есть свой текст.

2024-07-23 15:20 UTC, wonderjs requested changes
Всё хорошо, но нужна доработка модуля message

2024-07-23 15:20 UTC, wonderjs commented on js/filters.js
> +const filtersReset = () => mapFiltersForm.reset();
Называй функции с глагола - `resetFilters`

2024-07-23 15:20 UTC, wonderjs commented on js/message.js
> +  successMessageElement.classList.add('hidden');
На закрытии не удаляешь обработчики и не удаляешь элемент из дома. Получается, что при каждом вызове функции открытия будут вешаться дополнительные обработчики, но сообщение при этом показываться не будет, тк класс hidden ты там не удаляешь. Вспомни как делала в кекстаграмме

2024-07-23 15:20 UTC, wonderjs commented on js/reset.js
> +export { resetAll };
Этот модуль лучше назвать page и функцию resetPage

2024-07-23 15:20 UTC, wonderjs commented on js/map.js
> +const closePopup = () => {
Лучше сделать одну функцию resetMap и внутри нее закрывать попап и ставить маркер с исходную позицию

2024-07-23 15:20 UTC, wonderjs commented on js/main.js
> +    renderSimilarMarkers(ads.slice(0, SIMILAR_MARKERS_COUNT));
Можно в одном then писать несколько функций =) 
```
getData()
  .then((ads) => {
    renderSimilarMarkers(ads.slice(0, SIMILAR_MARKERS_COUNT));
    enableFilters();
  })
  .catch((err) => {
    showAlert(err.message);
  });
```

2024-07-26 08:30 UTC, DariaEgarmina commented on js/message.js
> +  successMessageElement.classList.add('hidden');
Это я уже делала в ночи, поэтому всё так :))

2024-07-29 09:41 UTC, wonderjs approved these changes

2024-07-29 09:41 UTC, wonderjs commented on js/api.js
> +  SEND_DATA: '/1',
тестировала ошибку и забыла убрать?

2024-07-29 09:41 UTC, merged